Monday-Morning/project-reclamation

docker-compose.yml
server/config/apolloServer.js
server/config/cors.js

- CORS does not work in staging due to crashing string check
- Dockerfile requires lowercase reponame

fix(env): CORS crashes in staging environment

---

server/schema/article/article.datasources.js

fix: search query index fix

---

server/schema/article/article.datasources.js

#136 
Sort article by createdAt

feat: sort article by createdAt

---

server/schema/user/user.datasources.js
server/schema/user/user.query.js
server/schema/user/user.resolver.js

feat: add query getUserByOldUserName

---

server/schema/user/user.datasources.js
server/schema/user/user.resolver.js

fix: create user mongodb transaction

---

server/schema/issue/issue.type.js

fix: get all articles in latest issue

---

server/schema/article/article.datasources.js
server/schema/article/article.query.js
server/schema/article/article.resolver.js

feat(query): get articles by year and month

---

server/schema/article/article.resolver.js
server/schema/user/user.datasources.js
server/schema/user/user.query.js
server/schema/user/user.resolver.js

feat: get list of user by account type

---

server/package.json
server/router/index.js
server/yarn.lock

feat: imagekit auth end point

---

server/router/index.js
server/utils/userAuth/index.js
server/utils/userAuth/permission.js

feat: auth check endpoint

---

server/schema/article/article.datasources.js
server/schema/article/article.query.js
server/schema/article/article.resolver.js

feat: count total no of articles

---

.github/workflows/eslint.yml
.github/workflows/prettier.yml
.github/workflows/setup.yml
server/env/.env.sample

fix: eslint, prettier and setup workflows

---

planning/v1/ROLES.md
server/schema/index.js
server/schema/media/media.datasources.js
server/schema/media/media.mutation.js
server/schema/media/media.query.js
server/schema/media/media.resolver.js
server/schema/media/media.schema.js
server/schema/media/media.type.js
server/utils/userAuth/index.js

feat (graphql):  add media section

---

server/schema/media/media.resolver.js

lint: fix lint issue in media resolver

---

server/schema/article/article.datasources.js

fix: add id fields in aggregation pipeline

---

server/schema/user/user.resolver.js

fix: create user permission check

---

server/env/.env.sample
server/router/index.js

feat: add route to get spotify access token

---

server/config/apolloServer.js
server/schema/common/session.enum.type.js
server/schema/company/company.datasources.js
server/schema/company/company.model.js
server/schema/company/company.mutation.js
server/schema/company/company.query.js
server/schema/company/company.resolver.js
server/schema/live/live.datasources.js
server/schema/live/live.model.js
server/schema/live/live.mutation.js
server/schema/live/live.query.js
server/schema/live/live.resolver.js
server/schema/live/live.type.js

feat: basic integration of live page

---

server/router/index.js

feat: add auth check to media end point

---

server/schema/tag/tag.type.js

https://github.com/Monday-Morning/project-tahiti/issues/406

fix: add id in tag

---

server/app.js
server/router/index.js
server/utils/userAuth/index.js
server/utils/userAuth/session.js

fix(context): creation failing for new users

---

server/yarn.lock
yarn.lock

chore: upgrade packages to latest minor-patch

---

server/config/imagekit.js
server/schema/media/media.datasources.js
server/schema/media/media.resolver.js
server/schema/user/user.datasources.js
server/schema/user/user.model.js
server/schema/user/user.mutation.js
server/schema/user/user.resolver.js
server/schema/user/user.type.js

chore: fix graphql user for boarding

---

server/config/apolloServer.js
server/schema/media/media.datasources.js
server/schema/media/media.resolver.js
server/schema/media/media.type.js
server/schema/user/user.datasources.js
server/schema/user/user.model.js
server/schema/user/user.mutation.js
server/schema/user/user.query.js
server/schema/user/user.resolver.js

- User flow for authentication (signup and sign in)
- User flow for webmail verification

feat: webmail authentication userflow

---

server/package.json
server/schema/article/article.resolver.js
server/yarn.lock
yarn.lock

- Pulled changes from main branch

chore: merge changes from main branch

---

server/env/.env.sample
server/schema/user/user.resolver.js
server/utils/userAuth/index.js
server/utils/userAuth/permission.js
server/utils/userAuth/session.js

- Add support for API Key based read queries for server-side builds and ISR.

feat: server API key access

---

server/schema/issue/issue.resolver.js

chore(issue): add typename in public fields

---

server/schema/user/user.resolver.js

fix(user): update list all user permission

---

server/yarn.lock

chore: update yarn lock
